//
//  Questions.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.4
//

import Foundation
import UIKit
import AWSDynamoDB

class Questions: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _questionID: String?
    var _answerOption1: String?
    var _answerOption2: String?
    var _answerOption3: String?
    var _answerOption4: String?
    var _createdDate: String?
    var _questionStatus: String?
    var _questionText: String?
    var _questionTitle: String?
    
    class func dynamoDBTableName() -> String {

        return "instaq-mobilehub-1215530306-Questions"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_questionID"
    }
    
    override class func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject] {
        return [
               "_userId" : "userId",
               "_questionID" : "questionID",
               "_answerOption1" : "answerOption1",
               "_answerOption2" : "answerOption2",
               "_answerOption3" : "answerOption3",
               "_answerOption4" : "answerOption4",
               "_createdDate" : "createdDate",
               "_questionStatus" : "questionStatus",
               "_questionText" : "questionText",
               "_questionTitle" : "questionTitle",
        ]
    }
}
