//
//  QuestionsTable.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.4
//

import Foundation
import UIKit
import AWSDynamoDB
import AWSMobileHubHelper

class QuestionsTable: NSObject, Table {
    
    var tableName: String
    var partitionKeyName: String
    var partitionKeyType: String
    var sortKeyName: String?
    var sortKeyType: String?
    var model: AWSDynamoDBObjectModel
    var indexes: [Index]
    var orderedAttributeKeys: [String] {
        return produceOrderedAttributeKeys(model)
    }
    var tableDisplayName: String {

        return "Questions"
    }
    
    override init() {

        model = Questions()
        
        tableName = model.classForCoder.dynamoDBTableName()
        partitionKeyName = model.classForCoder.hashKeyAttribute()
        partitionKeyType = "String"
        indexes = [

            QuestionsPrimaryIndex(),

            QuestionsQuestion(),
        ]
        if (model.classForCoder.respondsToSelector("rangeKeyAttribute")) {
            sortKeyName = model.classForCoder.rangeKeyAttribute!()
            sortKeyType = "String"
        }
        super.init()
    }
    
    /**
     * Converts the attribute name from data object format to table format.
     *
     * - parameter dataObjectAttributeName: data object attribute name
     * - returns: table attribute name
     */

    func tableAttributeName(dataObjectAttributeName: String) -> String {
        return Questions.JSONKeyPathsByPropertyKey()[dataObjectAttributeName] as! String
    }
    
    func getItemDescription() -> String {
        return "Find Item with userId = \(AWSIdentityManager.defaultIdentityManager().identityId!) and questionID = \("demo-questionID-500000")."
    }
    
    func getItemWithCompletionHandler(completionHandler: (response: AWSDynamoDBObjectModel?, error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.defaultDynamoDBObjectMapper()
        objectMapper.load(Questions.self, hashKey: AWSIdentityManager.defaultIdentityManager().identityId!, rangeKey: "demo-questionID-500000", completionHandler: {(response: AWSDynamoDBObjectModel?, error: NSError?) -> Void in
            dispatch_async(dispatch_get_main_queue(), {
                completionHandler(response: response, error: error)
            })
        })
    }
    
    func scanDescription() -> String {
        return "Show all items in the table."
    }
    
    func scanWithCompletionHandler(completionHandler: (response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.defaultDynamoDBObjectMapper()
        let scanExpression = AWSDynamoDBScanExpression()
        scanExpression.limit = 5

        objectMapper.scan(Questions.self, expression: scanExpression, completionHandler: {(response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void in
            dispatch_async(dispatch_get_main_queue(), {
                completionHandler(response: response, error: error)
            })
        })
    }
    
    func scanWithFilterDescription() -> String {
        return "Find all items with answerOption1 < \("demo-answerOption1-500000")."
    }
    
    func scanWithFilterWithCompletionHandler(completionHandler: (response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.defaultDynamoDBObjectMapper()
        let scanExpression = AWSDynamoDBScanExpression()
        
        scanExpression.filterExpression = "#answerOption1 < :answerOption1"
        scanExpression.expressionAttributeNames = ["#answerOption1": "answerOption1" ,]
        scanExpression.expressionAttributeValues = [":answerOption1": "demo-answerOption1-500000" ,]

        objectMapper.scan(Questions.self, expression: scanExpression, completionHandler: {(response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void in
            dispatch_async(dispatch_get_main_queue(), {
                completionHandler(response: response, error: error)
            })
        })
    }
    
    func insertSampleDataWithCompletionHandler(completionHandler: (errors: [NSError]?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.defaultDynamoDBObjectMapper()
        var errors: [NSError] = []
        let group: dispatch_group_t = dispatch_group_create()
        let numberOfObjects = 20
        

        let itemForGet = Questions()
        
        itemForGet._userId = AWSIdentityManager.defaultIdentityManager().identityId!
        itemForGet._questionID = "demo-questionID-500000"
        itemForGet._answerOption1 = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("answerOption1")
        itemForGet._answerOption2 = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("answerOption2")
        itemForGet._answerOption3 = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("answerOption3")
        itemForGet._answerOption4 = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("answerOption4")
        itemForGet._createdDate = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("createdDate")
        itemForGet._questionStatus = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("questionStatus")
        itemForGet._questionText = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("questionText")
        itemForGet._questionTitle = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("questionTitle")
        
        
        dispatch_group_enter(group)
        

        objectMapper.save(itemForGet, completionHandler: {(error: NSError?) -> Void in
            if error != nil {
                dispatch_async(dispatch_get_main_queue(), {
                    errors.append(error!)
                })
            }
            dispatch_group_leave(group)
        })
        
        for _ in 1..<numberOfObjects {

            let item: Questions = Questions()
            item._userId = AWSIdentityManager.defaultIdentityManager().identityId!
            item._questionID = NoSQLSampleDataGenerator.randomPartitionSampleStringWithAttributeName("questionID")
            item._answerOption1 = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("answerOption1")
            item._answerOption2 = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("answerOption2")
            item._answerOption3 = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("answerOption3")
            item._answerOption4 = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("answerOption4")
            item._createdDate = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("createdDate")
            item._questionStatus = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("questionStatus")
            item._questionText = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("questionText")
            item._questionTitle = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("questionTitle")
            
            dispatch_group_enter(group)
            
            objectMapper.save(item, completionHandler: {(error: NSError?) -> Void in
                if error != nil {
                    dispatch_async(dispatch_get_main_queue(), {
                        errors.append(error!)
                    })
                }
                dispatch_group_leave(group)
            })
        }
        
        dispatch_group_notify(group, dispatch_get_main_queue(), {
            if errors.count > 0 {
                completionHandler(errors: errors)
            }
            else {
                completionHandler(errors: nil)
            }
        })
    }
    
    func removeSampleDataWithCompletionHandler(completionHandler: (errors: [NSError]?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.defaultDynamoDBObjectMapper()
        let queryExpression = AWSDynamoDBQueryExpression()
        queryExpression.keyConditionExpression = "#userId = :userId"
        queryExpression.expressionAttributeNames = ["#userId": "userId"]
        queryExpression.expressionAttributeValues = [":userId": AWSIdentityManager.defaultIdentityManager().identityId!,]

        objectMapper.query(Questions.self, expression: queryExpression) { (response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void in
            if let error = error {
                dispatch_async(dispatch_get_main_queue(), {
                    completionHandler(errors: [error]);
                    })
            } else {
                var errors: [NSError] = []
                let group: dispatch_group_t = dispatch_group_create()
                for item in response!.items {
                    dispatch_group_enter(group)
                    objectMapper.remove(item, completionHandler: {(error: NSError?) -> Void in
                        if error != nil {
                            dispatch_async(dispatch_get_main_queue(), {
                                errors.append(error!)
                            })
                        }
                        dispatch_group_leave(group)
                    })
                }
                dispatch_group_notify(group, dispatch_get_main_queue(), {
                    if errors.count > 0 {
                        completionHandler(errors: errors)
                    }
                    else {
                        completionHandler(errors: nil)
                    }
                })
            }
        }
    }
    
    func updateItem(item: AWSDynamoDBObjectModel, completionHandler: (error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.defaultDynamoDBObjectMapper()
        

        let itemToUpdate: Questions = item as! Questions
        
        itemToUpdate._answerOption1 = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("answerOption1")
        itemToUpdate._answerOption2 = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("answerOption2")
        itemToUpdate._answerOption3 = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("answerOption3")
        itemToUpdate._answerOption4 = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("answerOption4")
        itemToUpdate._createdDate = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("createdDate")
        itemToUpdate._questionStatus = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("questionStatus")
        itemToUpdate._questionText = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("questionText")
        itemToUpdate._questionTitle = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("questionTitle")
        
        objectMapper.save(itemToUpdate, completionHandler: {(error: NSError?) -> Void in
            dispatch_async(dispatch_get_main_queue(), {
                completionHandler(error: error)
            })
        })
    }
    
    func removeItem(item: AWSDynamoDBObjectModel, completionHandler: (error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.defaultDynamoDBObjectMapper()
        
        objectMapper.remove(item, completionHandler: {(error: NSError?) -> Void in
            dispatch_async(dispatch_get_main_queue(), {
                completionHandler(error: error)
            })
        })
    }
}

class QuestionsPrimaryIndex: NSObject, Index {
    
    var indexName: String? {
        return nil
    }
    
    func supportedOperations() -> [String] {
        return [
            QueryWithPartitionKey,
            QueryWithPartitionKeyAndFilter,
            QueryWithPartitionKeyAndSortKey,
            QueryWithPartitionKeyAndSortKeyAndFilter,
        ]
    }
    
    func queryWithPartitionKeyDescription() -> String {
        return "Find all items with userId = \(AWSIdentityManager.defaultIdentityManager().identityId!)."
    }
    
    func queryWithPartitionKeyWithCompletionHandler(completionHandler: (response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.defaultDynamoDBObjectMapper()
        let queryExpression = AWSDynamoDBQueryExpression()
        
        queryExpression.keyConditionExpression = "#userId = :userId"
        queryExpression.expressionAttributeNames = ["#userId": "userId",]
        queryExpression.expressionAttributeValues = [":userId": AWSIdentityManager.defaultIdentityManager().identityId!,]

        objectMapper.query(Questions.self, expression: queryExpression, completionHandler: {(response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void in
            dispatch_async(dispatch_get_main_queue(), {
                completionHandler(response: response, error: error)
            })
        })
    }
    
    func queryWithPartitionKeyAndFilterDescription() -> String {
        return "Find all items with userId = \(AWSIdentityManager.defaultIdentityManager().identityId!) and answerOption1 > \("demo-answerOption1-500000")."
    }
    
    func queryWithPartitionKeyAndFilterWithCompletionHandler(completionHandler: (response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.defaultDynamoDBObjectMapper()
        let queryExpression = AWSDynamoDBQueryExpression()
        
        queryExpression.keyConditionExpression = "#userId = :userId"
        queryExpression.filterExpression = "#answerOption1 > :answerOption1"
        queryExpression.expressionAttributeNames = [
            "#userId": "userId",
            "#answerOption1": "answerOption1",
        ]
        queryExpression.expressionAttributeValues = [
            ":userId": AWSIdentityManager.defaultIdentityManager().identityId!,
            ":answerOption1": "demo-answerOption1-500000",
        ]
        

        objectMapper.query(Questions.self, expression: queryExpression, completionHandler: {(response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void in
            dispatch_async(dispatch_get_main_queue(), {
                completionHandler(response: response, error: error)
            })
        })
    }
    
    func queryWithPartitionKeyAndSortKeyDescription() -> String {
        return "Find all items with userId = \(AWSIdentityManager.defaultIdentityManager().identityId!) and questionID < \("demo-questionID-500000")."
    }
    
    func queryWithPartitionKeyAndSortKeyWithCompletionHandler(completionHandler: (response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.defaultDynamoDBObjectMapper()
        let queryExpression = AWSDynamoDBQueryExpression()
        
        queryExpression.keyConditionExpression = "#userId = :userId AND #questionID < :questionID"
        queryExpression.expressionAttributeNames = [
            "#userId": "userId",
            "#questionID": "questionID",
        ]
        queryExpression.expressionAttributeValues = [
            ":userId": AWSIdentityManager.defaultIdentityManager().identityId!,
            ":questionID": "demo-questionID-500000",
        ]
        

        objectMapper.query(Questions.self, expression: queryExpression, completionHandler: {(response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void in
            dispatch_async(dispatch_get_main_queue(), {
                completionHandler(response: response, error: error)
            })
        })
    }
    
    func queryWithPartitionKeyAndSortKeyAndFilterDescription() -> String {
        return "Find all items with userId = \(AWSIdentityManager.defaultIdentityManager().identityId!), questionID < \("demo-questionID-500000"), and answerOption1 > \("demo-answerOption1-500000")."
    }
    
    func queryWithPartitionKeyAndSortKeyAndFilterWithCompletionHandler(completionHandler: (response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.defaultDynamoDBObjectMapper()
        let queryExpression = AWSDynamoDBQueryExpression()
        
        queryExpression.keyConditionExpression = "#userId = :userId AND #questionID < :questionID"
        queryExpression.filterExpression = "#answerOption1 > :answerOption1"
        queryExpression.expressionAttributeNames = [
            "#userId": "userId",
            "#questionID": "questionID",
            "#answerOption1": "answerOption1",
        ]
        queryExpression.expressionAttributeValues = [
            ":userId": AWSIdentityManager.defaultIdentityManager().identityId!,
            ":questionID": "demo-questionID-500000",
            ":answerOption1": "demo-answerOption1-500000",
        ]
        

        objectMapper.query(Questions.self, expression: queryExpression, completionHandler: {(response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void in
            dispatch_async(dispatch_get_main_queue(), {
                completionHandler(response: response, error: error)
            })
        })
    }
}

class QuestionsQuestion: NSObject, Index {
    
    var indexName: String? {

        return "Question"
    }
    
    func supportedOperations() -> [String] {
        return [
            QueryWithPartitionKey,
            QueryWithPartitionKeyAndFilter,
            QueryWithPartitionKeyAndSortKey,
            QueryWithPartitionKeyAndSortKeyAndFilter,
        ]
    }
    
    func queryWithPartitionKeyDescription() -> String {
        return "Find all items with questionID = \("demo-questionID-3")."
    }
    
    func queryWithPartitionKeyWithCompletionHandler(completionHandler: (response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.defaultDynamoDBObjectMapper()
        let queryExpression = AWSDynamoDBQueryExpression()
        

        queryExpression.indexName = "Question"
        queryExpression.keyConditionExpression = "#questionID = :questionID"
        queryExpression.expressionAttributeNames = ["#questionID": "questionID",]
        queryExpression.expressionAttributeValues = [":questionID": "demo-questionID-3",]

        objectMapper.query(Questions.self, expression: queryExpression, completionHandler: {(response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void in
            dispatch_async(dispatch_get_main_queue(), {
                completionHandler(response: response, error: error)
            })
        })
    }
    
    func queryWithPartitionKeyAndFilterDescription() -> String {
        return "Find all items with questionID = \("demo-questionID-3") and answerOption1 > \("demo-answerOption1-500000")."
    }
    
    func queryWithPartitionKeyAndFilterWithCompletionHandler(completionHandler: (response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.defaultDynamoDBObjectMapper()
        let queryExpression = AWSDynamoDBQueryExpression()
        

        queryExpression.indexName = "Question"
        queryExpression.keyConditionExpression = "#questionID = :questionID"
        queryExpression.filterExpression = "#answerOption1 > :answerOption1"
        queryExpression.expressionAttributeNames = [
            "#questionID": "questionID",
            "#answerOption1": "answerOption1",
        ]
        queryExpression.expressionAttributeValues = [
            ":questionID": "demo-questionID-3",
            ":answerOption1": "demo-answerOption1-500000",
        ]
        

        objectMapper.query(Questions.self, expression: queryExpression, completionHandler: {(response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void in
            dispatch_async(dispatch_get_main_queue(), {
                completionHandler(response: response, error: error)
            })
        })
    }
    
    func queryWithPartitionKeyAndSortKeyDescription() -> String {
        return "Find all items with questionID = \("demo-questionID-3") and questionText < \("demo-questionText-500000")."
    }
    
    func queryWithPartitionKeyAndSortKeyWithCompletionHandler(completionHandler: (response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.defaultDynamoDBObjectMapper()
        let queryExpression = AWSDynamoDBQueryExpression()
        

        queryExpression.indexName = "Question"
        queryExpression.keyConditionExpression = "#questionID = :questionID AND #questionText < :questionText"
        queryExpression.expressionAttributeNames = [
            "#questionID": "questionID",
            "#questionText": "questionText",
        ]
        queryExpression.expressionAttributeValues = [
            ":questionID": "demo-questionID-3",
            ":questionText": "demo-questionText-500000",
        ]
        

        objectMapper.query(Questions.self, expression: queryExpression, completionHandler: {(response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void in
            dispatch_async(dispatch_get_main_queue(), {
                completionHandler(response: response, error: error)
            })
        })
    }
    
    func queryWithPartitionKeyAndSortKeyAndFilterDescription() -> String {
        return "Find all items with questionID = \("demo-questionID-3"), questionText < \("demo-questionText-500000"), and answerOption1 > \("demo-answerOption1-500000")."
    }
    
    func queryWithPartitionKeyAndSortKeyAndFilterWithCompletionHandler(completionHandler: (response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.defaultDynamoDBObjectMapper()
        let queryExpression = AWSDynamoDBQueryExpression()
        

        queryExpression.indexName = "Question"
        queryExpression.keyConditionExpression = "#questionID = :questionID AND #questionText < :questionText"
        queryExpression.filterExpression = "#answerOption1 > :answerOption1"
        queryExpression.expressionAttributeNames = [
            "#questionID": "questionID",
            "#questionText": "questionText",
            "#answerOption1": "answerOption1",
        ]
        queryExpression.expressionAttributeValues = [
            ":questionID": "demo-questionID-3",
            ":questionText": "demo-questionText-500000",
            ":answerOption1": "demo-answerOption1-500000",
        ]
        

        objectMapper.query(Questions.self, expression: queryExpression, completionHandler: {(response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void in
            dispatch_async(dispatch_get_main_queue(), {
                completionHandler(response: response, error: error)
            })
        })
    }
}
